### ISSUE TITLE
java.lang.ClassNotFoundException: at/mukprojects/giphy4j/Giphy

### ISSUE THREAD

**Issue by martinprejsa** [keshrath/Giphy4J#6]
`java.lang.NoClassDefFoundError: at/mukprojects/giphy4j/Giphy
        at me.WattMann.listeners.GifCommand.onMessageReceived(GifCommand.java:21)
        at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:417)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1051)
        at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:911)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.ClassNotFoundException: at.mukprojects.giphy4j.Giphy
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 16 more`

[my code](https://hastebin.com/ohuzilikok.cs)

**Comment by martinprejsa** [comment]
Nevermind. it fixed itself
